// <auto-generated />
using System;
using BookStoreWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418221708_AddPaymentMethod")]
    partial class AddPaymentMethod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("BookStoreWeb.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHangs", (string)null);
                });

            modelBuilder.Entity("BookStoreWeb.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHangs", (string)null);
                });

            modelBuilder.Entity("BookStoreWeb.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs", (string)null);
                });

            modelBuilder.Entity("BookStoreWeb.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConHieuLuc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TacGia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TheLoai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPhams", (string)null);
                });

            modelBuilder.Entity("BookStoreWeb.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("BookStoreWeb.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreWeb.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BookStoreWeb.Models.DonHang", b =>
                {
                    b.HasOne("BookStoreWeb.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookStoreWeb.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
